# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot_2r.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetGrafica = QtWidgets.QWidget(Form)
        self.widgetGrafica.setObjectName("widgetGrafica")
        self.horizontalLayout.addWidget(self.widgetGrafica)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelX = QtWidgets.QLabel(Form)
        self.labelX.setObjectName("labelX")
